import type { DistrictMaster, Guardian, MandalMaster, RelationshipMaster, Reminder, SchoolMaster, Sponsor, SponsorView, StateMaster, Student, StudentSponsor, StudentView, User, VillageMaster } from '../types';
import studentBoy from '../assets/student-boy.svg';
import studentBoy2 from '../assets/student-boy-2.svg';
import studentGirl from '../assets/student-girl.svg';
import studentGirl2 from '../assets/student-girl-2.svg';

export const delay = (ms = 450) => new Promise<void>((resolve) => setTimeout(resolve, ms));

export const MOCK_STATES: StateMaster[] = [
  { st_id: 1, st_name: 'Telangana', created_at: '2024-01-01', updated_at: null },
  { st_id: 2, st_name: 'Andhra Pradesh', created_at: '2024-01-01', updated_at: null },
];
export const MOCK_DISTRICTS: DistrictMaster[] = [
  { dist_id: 1, dist_name: 'Warangal', st_id: 1, created_at: '2024-01-01', updated_at: null },
  { dist_id: 2, dist_name: 'Karimnagar', st_id: 1, created_at: '2024-01-01', updated_at: null },
  { dist_id: 3, dist_name: 'Nalgonda', st_id: 1, created_at: '2024-01-01', updated_at: null },
];
export const MOCK_MANDALS: MandalMaster[] = [
  { mndl_id: 1, mndl_name: 'Hanamkonda', dist_id: 1, created_at: '2024-01-01', updated_at: null },
  { mndl_id: 2, mndl_name: 'Jammikunta', dist_id: 2, created_at: '2024-01-01', updated_at: null },
  { mndl_id: 3, mndl_name: 'Miryalaguda', dist_id: 3, created_at: '2024-01-01', updated_at: null },
];
export const MOCK_VILLAGES: VillageMaster[] = [
  { vil_id: 1, vil_name: 'Dharmasagar', vil_pincode: 506001, mndl_id: 1, created_at: '2024-01-01', updated_at: null },
  { vil_id: 2, vil_name: 'Gangadhara', vil_pincode: 505122, mndl_id: 2, created_at: '2024-01-01', updated_at: null },
  { vil_id: 3, vil_name: 'Nereducharla', vil_pincode: 508112, mndl_id: 3, created_at: '2024-01-01', updated_at: null },
];
export const MOCK_SCHOOLS: SchoolMaster[] = [
  { sch_id: 1, sch_name: 'ZP High School Warangal', sch_address: 'Hanamkonda, Warangal, Telangana 506001', vil_id: 1, created_at: '2024-01-01', updated_at: null },
  { sch_id: 2, sch_name: "St. Joseph's High School", sch_address: 'Jammikunta, Karimnagar, Telangana 505122', vil_id: 2, created_at: '2024-01-01', updated_at: null },
  { sch_id: 3, sch_name: 'Kasturba Vidyalaya', sch_address: 'Nereducharla, Nalgonda, Telangana 508112', vil_id: 3, created_at: '2024-01-01', updated_at: null },
];
export const MOCK_RELATIONSHIPS: RelationshipMaster[] = [
  { relationship_id: 1, relationship_name: 'Mother', relationship_code: 'MTH', description: null, is_active: true, created_at: '2024-01-01', updated_at: null },
  { relationship_id: 2, relationship_name: 'Father', relationship_code: 'FTH', description: null, is_active: true, created_at: '2024-01-01', updated_at: null },
  { relationship_id: 3, relationship_name: 'Uncle', relationship_code: 'UNC', description: null, is_active: true, created_at: '2024-01-01', updated_at: null },
  { relationship_id: 4, relationship_name: 'Aunt', relationship_code: 'ANT', description: null, is_active: true, created_at: '2024-01-01', updated_at: null },
  { relationship_id: 5, relationship_name: 'Grandparent', relationship_code: 'GRP', description: null, is_active: true, created_at: '2024-01-01', updated_at: null },
];

export let MOCK_USERS: User[] = [
  { user_id: 1, username: 'Admin User', password: 'hashed_pw', email_id: 'admin@sahofoundation.org', role: 'Admin', is_active: true, created_at: '2024-01-10', created_by: 'system', modified_at: null, modified_by: null },
  { user_id: 2, username: 'Suresh Verma', password: 'hashed_pw', email_id: 'suresh.v@sahofoundation.org', role: 'Admin', is_active: true, created_at: '2024-03-15', created_by: 'admin', modified_at: null, modified_by: null },
  { user_id: 3, username: 'Preethi Nair', password: 'hashed_pw', email_id: 'preethi.n@sahofoundation.org', role: 'Volunteer', is_active: true, created_at: '2024-06-20', created_by: 'admin', modified_at: null, modified_by: null },
];
export let MOCK_GUARDIANS: Guardian[] = [
  { guardian_id: 1, first_name: 'Sunita', middle_name: null, last_name: 'Reddy', phone_number: '9811001001', relation: 1, occ: 'Tailor', addr: 'Dharmasagar, Warangal', created_at: '2024-02-01', updated_at: null },
  { guardian_id: 2, first_name: 'Ramesh', middle_name: null, last_name: 'Kumar', phone_number: '9811001002', relation: 2, occ: 'Auto Driver', addr: 'Gangadhara, Karimnagar', created_at: '2024-02-02', updated_at: null },
  { guardian_id: 3, first_name: 'Vijaya', middle_name: null, last_name: 'Lakshmi', phone_number: '9811001003', relation: 1, occ: 'Domestic Worker', addr: 'Dharmasagar, Warangal', created_at: '2024-02-03', updated_at: null },
  { guardian_id: 4, first_name: 'Srinivas', middle_name: null, last_name: 'Rao', phone_number: '9811001004', relation: 2, occ: 'Farmer', addr: 'Nereducharla, Nalgonda', created_at: '2024-02-04', updated_at: null },
  { guardian_id: 5, first_name: 'Geeta', middle_name: null, last_name: 'Singh', phone_number: '9811001005', relation: 1, occ: 'Vegetable Vendor', addr: 'Dharmasagar, Warangal', created_at: '2024-02-05', updated_at: null },
];
const BASE_STUDENTS: Student[] = [
  { student_id: 1, first_name: 'Priya', middle_name: null, last_name: 'Reddy', email: 'priya.reddy@example.com', dob: '2008-03-15', gender: 'Female', aadhaar_number: '123456789012', caste: 'BC-B', religion: 'Hindu', blood_group: 'O+', sch_id: 1, class_id: '8th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-03-01', created_by: 'admin', modified_at: null, modified_by: null },
  { student_id: 2, first_name: 'Arjun', middle_name: null, last_name: 'Kumar', email: 'arjun.kumar@example.com', dob: '2009-07-22', gender: 'Male', aadhaar_number: '234567890123', caste: 'OC', religion: 'Hindu', blood_group: 'A+', sch_id: 2, class_id: '7th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy, is_active: true, created_at: '2024-03-02', created_by: 'admin', modified_at: null, modified_by: null },
  { student_id: 3, first_name: 'Meena', middle_name: null, last_name: 'Devi', email: 'meena.devi@example.com', dob: '2007-11-08', gender: 'Female', aadhaar_number: '345678901234', caste: 'SC', religion: 'Hindu', blood_group: 'B+', sch_id: 1, class_id: '9th', guardian_id: 3, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-03-03', created_by: 'admin', modified_at: null, modified_by: null },
  { student_id: 4, first_name: 'Ravi', middle_name: null, last_name: 'Shankar', email: 'ravi.shankar@example.com', dob: '2010-01-30', gender: 'Male', aadhaar_number: '456789012345', caste: 'BC-A', religion: 'Hindu', blood_group: 'AB+', sch_id: 3, class_id: '6th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-03-04', created_by: 'admin', modified_at: null, modified_by: null },
  { student_id: 5, first_name: 'Lakshmi', middle_name: null, last_name: 'Bai', email: 'lakshmi.bai@example.com', dob: '2008-05-12', gender: 'Female', aadhaar_number: '567890123456', caste: 'SC', religion: 'Hindu', blood_group: 'O-', sch_id: 2, class_id: '8th', guardian_id: 4, orphan_status: 'Orphan', image_url: studentGirl, is_active: true, created_at: '2024-03-05', created_by: 'admin', modified_at: null, modified_by: null },
  { student_id: 6, first_name: 'Kiran', middle_name: null, last_name: 'Babu', email: 'kiran.babu@example.com', dob: '2009-09-18', gender: 'Male', aadhaar_number: '678901234567', caste: 'OC', religion: 'Muslim', blood_group: 'B-', sch_id: 3, class_id: '7th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: false, created_at: '2024-03-06', created_by: 'admin', modified_at: null, modified_by: null },
  { student_id: 7, first_name: 'Anitha', middle_name: null, last_name: 'Singh', email: 'anitha.singh@example.com', dob: '2011-02-28', gender: 'Female', aadhaar_number: '789012345678', caste: 'BC-C', religion: 'Hindu', blood_group: 'A-', sch_id: 1, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-03-07', created_by: 'admin', modified_at: null, modified_by: null },
];

// Some mock rows don't specify `created_by`; we default it when building MOCK_STUDENTS.
const ADDITIONAL_STUDENTS: Omit<Student, 'student_id' | 'created_by'>[] = [
  { first_name: 'Sneha', middle_name: null, last_name: 'Reddy', email: 'sneha.reddy@example.com', dob: '2010-04-02', gender: 'Female', aadhaar_number: '890123456789', caste: 'BC-B', religion: 'Hindu', blood_group: 'A+', sch_id: 1, class_id: '6th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-03-08', modified_at: null, modified_by: null },
  { first_name: 'Manish', middle_name: null, last_name: 'Kumar', email: 'manish.kumar@example.com', dob: '2009-08-11', gender: 'Male', aadhaar_number: '901234567890', caste: 'OC', religion: 'Hindu', blood_group: 'B+', sch_id: 2, class_id: '7th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy, is_active: true, created_at: '2024-03-09', modified_at: null, modified_by: null },
  { first_name: 'Nithya', middle_name: null, last_name: 'Rao', email: 'nithya.rao@example.com', dob: '2008-12-20', gender: 'Female', aadhaar_number: '012345678901', caste: 'SC', religion: 'Hindu', blood_group: 'O-', sch_id: 3, class_id: '8th', guardian_id: 4, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-03-10', modified_at: null, modified_by: null },
  { first_name: 'Sandeep', middle_name: null, last_name: 'Patel', email: 'sandeep.patel@example.com', dob: '2010-05-19', gender: 'Male', aadhaar_number: '112345678902', caste: 'BC-A', religion: 'Hindu', blood_group: 'AB+', sch_id: 1, class_id: '6th', guardian_id: 1, orphan_status: 'Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-03-11', modified_at: null, modified_by: null },
  { first_name: 'Priyanka', middle_name: null, last_name: 'Sharma', email: 'priyanka.sharma@example.com', dob: '2009-03-24', gender: 'Female', aadhaar_number: '212345678903', caste: 'OC', religion: 'Hindu', blood_group: 'A-', sch_id: 2, class_id: '7th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-03-12', modified_at: null, modified_by: null },
  { first_name: 'Vikram', middle_name: null, last_name: 'Singh', email: 'vikram.singh@example.com', dob: '2008-09-06', gender: 'Male', aadhaar_number: '312345678904', caste: 'BC-B', religion: 'Sikh', blood_group: 'B-', sch_id: 3, class_id: '8th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy, is_active: true, created_at: '2024-03-13', modified_at: null, modified_by: null },
  { first_name: 'Radhika', middle_name: null, last_name: 'Das', email: 'radhika.das@example.com', dob: '2011-01-17', gender: 'Female', aadhaar_number: '412345678905', caste: 'SC', religion: 'Hindu', blood_group: 'O+', sch_id: 1, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-03-14', modified_at: null, modified_by: null },
  { first_name: 'Deepak', middle_name: null, last_name: 'Yadav', email: 'deepak.yadav@example.com', dob: '2009-10-13', gender: 'Male', aadhaar_number: '512345678906', caste: 'OBC', religion: 'Hindu', blood_group: 'A+', sch_id: 2, class_id: '7th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: false, created_at: '2024-03-15', modified_at: null, modified_by: null },
  { first_name: 'Asha', middle_name: null, last_name: 'Chopra', email: 'asha.chopra@example.com', dob: '2008-07-25', gender: 'Female', aadhaar_number: '612345678907', caste: 'BC-C', religion: 'Hindu', blood_group: 'AB-', sch_id: 3, class_id: '8th', guardian_id: 4, orphan_status: 'Orphan', image_url: studentGirl, is_active: true, created_at: '2024-03-16', modified_at: null, modified_by: null },
  { first_name: 'Harsha', middle_name: null, last_name: 'Prasad', email: 'harsha.prasad@example.com', dob: '2010-11-09', gender: 'Male', aadhaar_number: '712345678908', caste: 'OC', religion: 'Hindu', blood_group: 'B+', sch_id: 1, class_id: '6th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: true, created_at: '2024-03-17', modified_at: null, modified_by: null },
  { first_name: 'Swetha', middle_name: null, last_name: 'Nair', email: 'swetha.nair@example.com', dob: '2009-02-13', gender: 'Female', aadhaar_number: '812345678909', caste: 'BC-A', religion: 'Hindu', blood_group: 'O-', sch_id: 2, class_id: '7th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-03-18', modified_at: null, modified_by: null },
  { first_name: 'Karthik', middle_name: null, last_name: 'Reddy', email: 'karthik.reddy@example.com', dob: '2008-06-14', gender: 'Male', aadhaar_number: '912345678910', caste: 'BC-B', religion: 'Hindu', blood_group: 'A+', sch_id: 3, class_id: '8th', guardian_id: 1, orphan_status: 'Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-03-19', modified_at: null, modified_by: null },
  { first_name: 'Neha', middle_name: null, last_name: 'Kaur', email: 'neha.kaur@example.com', dob: '2011-05-26', gender: 'Female', aadhaar_number: '101234567891', caste: 'SC', religion: 'Sikh', blood_group: 'B-', sch_id: 1, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-03-20', modified_at: null, modified_by: null },
  { first_name: 'Vivek', middle_name: null, last_name: 'Gupta', email: 'vivek.gupta@example.com', dob: '2009-04-06', gender: 'Male', aadhaar_number: '111234567892', caste: 'OC', religion: 'Hindu', blood_group: 'AB+', sch_id: 2, class_id: '7th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: true, created_at: '2024-03-21', modified_at: null, modified_by: null },
  { first_name: 'Priya', middle_name: null, last_name: 'Nandini', email: 'priya.nandini@example.com', dob: '2010-08-28', gender: 'Female', aadhaar_number: '121234567893', caste: 'BC-A', religion: 'Hindu', blood_group: 'A-', sch_id: 3, class_id: '6th', guardian_id: 4, orphan_status: 'Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-03-22', modified_at: null, modified_by: null },
  { first_name: 'Rahul', middle_name: null, last_name: 'Sharma', email: 'rahul.sharma@example.com', dob: '2008-10-19', gender: 'Male', aadhaar_number: '131234567894', caste: 'OC', religion: 'Hindu', blood_group: 'B+', sch_id: 1, class_id: '8th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: false, created_at: '2024-03-23', modified_at: null, modified_by: null },
  { first_name: 'Aarti', middle_name: null, last_name: 'Singh', email: 'aarti.singh@example.com', dob: '2009-01-13', gender: 'Female', aadhaar_number: '141234567895', caste: 'SC', religion: 'Hindu', blood_group: 'O+', sch_id: 2, class_id: '7th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-03-24', modified_at: null, modified_by: null },
  { first_name: 'Manju', middle_name: null, last_name: 'Verma', email: 'manju.verma@example.com', dob: '2011-06-02', gender: 'Female', aadhaar_number: '151234567896', caste: 'BC-C', religion: 'Hindu', blood_group: 'AB-', sch_id: 3, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-03-25', modified_at: null, modified_by: null },
  { first_name: 'Rohan', middle_name: null, last_name: 'Patel', email: 'rohan.patel@example.com', dob: '2008-11-18', gender: 'Male', aadhaar_number: '161234567897', caste: 'OC', religion: 'Hindu', blood_group: 'A+', sch_id: 1, class_id: '8th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy, is_active: true, created_at: '2024-03-26', modified_at: null, modified_by: null },
  { first_name: 'Sakshi', middle_name: null, last_name: 'Reddy', email: 'sakshi.reddy@example.com', dob: '2009-07-10', gender: 'Female', aadhaar_number: '171234567898', caste: 'BC-B', religion: 'Hindu', blood_group: 'A-', sch_id: 2, class_id: '7th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-03-27', modified_at: null, modified_by: null },
  { first_name: 'Kunal', middle_name: null, last_name: 'Mehta', email: 'kunal.mehta@example.com', dob: '2010-09-09', gender: 'Male', aadhaar_number: '181234567899', caste: 'BC-A', religion: 'Jain', blood_group: 'B-', sch_id: 3, class_id: '6th', guardian_id: 4, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-03-28', modified_at: null, modified_by: null },
  { first_name: 'Mala', middle_name: null, last_name: 'Sharma', email: 'mala.sharma@example.com', dob: '2008-05-21', gender: 'Female', aadhaar_number: '191234567890', caste: 'SC', religion: 'Hindu', blood_group: 'O+', sch_id: 1, class_id: '8th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-03-29', modified_at: null, modified_by: null },
  { first_name: 'Ajay', middle_name: null, last_name: 'Kumar', email: 'ajay.kumar21@example.com', dob: '2011-03-11', gender: 'Male', aadhaar_number: '201234567891', caste: 'BC-B', religion: 'Hindu', blood_group: 'AB+', sch_id: 2, class_id: '5th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: true, created_at: '2024-03-30', modified_at: null, modified_by: null },
  { first_name: 'Jaya', middle_name: null, last_name: 'Krishna', email: 'jaya.krishna@example.com', dob: '2009-12-04', gender: 'Female', aadhaar_number: '211234567892', caste: 'OC', religion: 'Hindu', blood_group: 'A-', sch_id: 3, class_id: '7th', guardian_id: 4, orphan_status: 'Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-03-31', modified_at: null, modified_by: null },
  { first_name: 'Ashok', middle_name: null, last_name: 'Verma', email: 'ashok.verma@example.com', dob: '2008-07-01', gender: 'Male', aadhaar_number: '221234567893', caste: 'SC', religion: 'Hindu', blood_group: 'O-', sch_id: 1, class_id: '8th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: true, created_at: '2024-04-01', modified_at: null, modified_by: null },
  { first_name: 'Simran', middle_name: null, last_name: 'Kaur', email: 'simran.kaur@example.com', dob: '2010-01-25', gender: 'Female', aadhaar_number: '231234567894', caste: 'BC-A', religion: 'Sikh', blood_group: 'B+', sch_id: 2, class_id: '6th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-04-02', modified_at: null, modified_by: null },
  { first_name: 'Ritesh', middle_name: null, last_name: 'Patel', email: 'ritesh.patel@example.com', dob: '2009-02-28', gender: 'Male', aadhaar_number: '241234567895', caste: 'OC', religion: 'Hindu', blood_group: 'A+', sch_id: 3, class_id: '7th', guardian_id: 4, orphan_status: 'Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-04-03', modified_at: null, modified_by: null },
  { first_name: 'Neelam', middle_name: null, last_name: 'Sharma', email: 'neelam.sharma@example.com', dob: '2011-09-17', gender: 'Female', aadhaar_number: '251234567896', caste: 'BC-B', religion: 'Hindu', blood_group: 'A-', sch_id: 1, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-04-04', modified_at: null, modified_by: null },
  { first_name: 'Sachin', middle_name: null, last_name: 'Gupta', email: 'sachin.gupta@example.com', dob: '2008-10-30', gender: 'Male', aadhaar_number: '261234567897', caste: 'OC', religion: 'Hindu', blood_group: 'B-', sch_id: 2, class_id: '8th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: true, created_at: '2024-04-05', modified_at: null, modified_by: null },
  { first_name: 'Radha', middle_name: null, last_name: 'Devi', email: 'radha.devi@example.com', dob: '2010-06-20', gender: 'Female', aadhaar_number: '271234567898', caste: 'SC', religion: 'Hindu', blood_group: 'O+', sch_id: 3, class_id: '6th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-04-06', modified_at: null, modified_by: null },
  { first_name: 'Kavita', middle_name: null, last_name: 'Sharma', email: 'kavita.sharma@example.com', dob: '2009-11-05', gender: 'Female', aadhaar_number: '281234567899', caste: 'BC-A', religion: 'Hindu', blood_group: 'AB+', sch_id: 1, class_id: '7th', guardian_id: 5, orphan_status: 'Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-04-07', modified_at: null, modified_by: null },
  { first_name: 'Abhishek', middle_name: null, last_name: 'Varma', email: 'abhishek.varma@example.com', dob: '2008-08-15', gender: 'Male', aadhaar_number: '291234567890', caste: 'OC', religion: 'Hindu', blood_group: 'A+', sch_id: 2, class_id: '8th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-04-08', modified_at: null, modified_by: null },
  { first_name: 'Divya', middle_name: null, last_name: 'Reddy', email: 'divya.reddy@example.com', dob: '2011-02-19', gender: 'Female', aadhaar_number: '301234567891', caste: 'BC-B', religion: 'Hindu', blood_group: 'O-', sch_id: 3, class_id: '5th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-04-09', modified_at: null, modified_by: null },
  { first_name: 'Nikhil', middle_name: null, last_name: 'Shah', email: 'nikhil.shah@example.com', dob: '2009-03-29', gender: 'Male', aadhaar_number: '311234567892', caste: 'BC-C', religion: 'Jain', blood_group: 'B+', sch_id: 1, class_id: '7th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: true, created_at: '2024-04-10', modified_at: null, modified_by: null },
  { first_name: 'Mohana', middle_name: null, last_name: 'Reddy', email: 'mohana.reddy@example.com', dob: '2010-05-07', gender: 'Female', aadhaar_number: '321234567893', caste: 'BC-B', religion: 'Hindu', blood_group: 'A-', sch_id: 2, class_id: '6th', guardian_id: 1, orphan_status: 'Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-04-11', modified_at: null, modified_by: null },
  { first_name: 'Gaurav', middle_name: null, last_name: 'Rao', email: 'gaurav.rao@example.com', dob: '2008-09-01', gender: 'Male', aadhaar_number: '331234567894', caste: 'OC', religion: 'Hindu', blood_group: 'B-', sch_id: 3, class_id: '8th', guardian_id: 4, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-04-12', modified_at: null, modified_by: null },
  { first_name: 'Sheetal', middle_name: null, last_name: 'Patel', email: 'sheetal.patel@example.com', dob: '2011-04-12', gender: 'Female', aadhaar_number: '341234567895', caste: 'BC-A', religion: 'Hindu', blood_group: 'AB-', sch_id: 1, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-04-13', modified_at: null, modified_by: null },
  { first_name: 'Rohan', middle_name: null, last_name: 'Jha', email: 'rohan.jha@example.com', dob: '2009-08-28', gender: 'Male', aadhaar_number: '351234567896', caste: 'OC', religion: 'Hindu', blood_group: 'A+', sch_id: 2, class_id: '7th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy, is_active: true, created_at: '2024-04-14', modified_at: null, modified_by: null },
  { first_name: 'Archana', middle_name: null, last_name: ' Sharma', email: 'archana.sharma@example.com', dob: '2010-12-09', gender: 'Female', aadhaar_number: '361234567897', caste: 'SC', religion: 'Hindu', blood_group: 'O+', sch_id: 3, class_id: '6th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-04-15', modified_at: null, modified_by: null },
  { first_name: 'Anil', middle_name: null, last_name: 'Kumar', email: 'anil.kumar@example.com', dob: '2008-06-01', gender: 'Male', aadhaar_number: '371234567898', caste: 'BC-B', religion: 'Hindu', blood_group: 'B+', sch_id: 1, class_id: '8th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: true, created_at: '2024-04-16', modified_at: null, modified_by: null },
  { first_name: 'Heena', middle_name: null, last_name: 'Shah', email: 'heena.shah@example.com', dob: '2011-09-19', gender: 'Female', aadhaar_number: '381234567899', caste: 'BC-A', religion: 'Hindu', blood_group: 'A-', sch_id: 1, class_id: '5th', guardian_id: 5, orphan_status: 'Orphan', image_url: studentGirl, is_active: true, created_at: '2024-04-17', modified_at: null, modified_by: null },
  { first_name: 'Praveen', middle_name: null, last_name: 'Rao', email: 'praveen.rao@example.com', dob: '2009-07-03', gender: 'Male', aadhaar_number: '391234567890', caste: 'OC', religion: 'Hindu', blood_group: 'A+', sch_id: 2, class_id: '7th', guardian_id: 4, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-04-18', modified_at: null, modified_by: null },
  { first_name: 'Maya', middle_name: null, last_name: 'Bose', email: 'maya.bose@example.com', dob: '2010-03-28', gender: 'Female', aadhaar_number: '401234567891', caste: 'BC-B', religion: 'Hindu', blood_group: 'O-', sch_id: 3, class_id: '6th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-04-19', modified_at: null, modified_by: null },
  { first_name: 'Arun', middle_name: null, last_name: 'Patel', email: 'arun.patel@example.com', dob: '2008-07-31', gender: 'Male', aadhaar_number: '411234567892', caste: 'OC', religion: 'Hindu', blood_group: 'AB+', sch_id: 2, class_id: '8th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy, is_active: true, created_at: '2024-04-20', modified_at: null, modified_by: null },
  { first_name: 'Kavya', middle_name: null, last_name: 'Sharma', email: 'kavya.sharma@example.com', dob: '2011-11-11', gender: 'Female', aadhaar_number: '421234567893', caste: 'SC', religion: 'Hindu', blood_group: 'AB-', sch_id: 1, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-04-21', modified_at: null, modified_by: null },
  { first_name: 'Siddharth', middle_name: null, last_name: 'Reddy', email: 'siddharth.reddy@example.com', dob: '2009-05-17', gender: 'Male', aadhaar_number: '431234567894', caste: 'BC-A', religion: 'Hindu', blood_group: 'B-', sch_id: 3, class_id: '7th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-04-22', modified_at: null, modified_by: null },
  { first_name: 'Isha', middle_name: null, last_name: 'Gupta', email: 'isha.gupta@example.com', dob: '2010-08-05', gender: 'Female', aadhaar_number: '441234567895', caste: 'BC-B', religion: 'Hindu', blood_group: 'A+', sch_id: 2, class_id: '6th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-04-23', modified_at: null, modified_by: null },
  { first_name: 'Ankit', middle_name: null, last_name: 'Singh', email: 'ankit.singh@example.com', dob: '2008-10-12', gender: 'Male', aadhaar_number: '451234567896', caste: 'OC', religion: 'Hindu', blood_group: 'A+', sch_id: 1, class_id: '8th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy, is_active: false, created_at: '2024-04-24', modified_at: null, modified_by: null },
  { first_name: 'Rekha', middle_name: null, last_name: 'Sharma', email: 'rekha.sharma@example.com', dob: '2011-07-06', gender: 'Female', aadhaar_number: '461234567897', caste: 'SC', religion: 'Hindu', blood_group: 'O+', sch_id: 3, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-04-25', modified_at: null, modified_by: null },
  { first_name: 'Naveen', middle_name: null, last_name: 'Reddy', email: 'naveen.reddy@example.com', dob: '2009-09-20', gender: 'Male', aadhaar_number: '471234567898', caste: 'BC-B', religion: 'Hindu', blood_group: 'B-', sch_id: 2, class_id: '7th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-04-26', modified_at: null, modified_by: null },
  { first_name: 'Shruti', middle_name: null, last_name: 'Malhotra', email: 'shruti.malhotra@example.com', dob: '2010-12-29', gender: 'Female', aadhaar_number: '481234567899', caste: 'BC-A', religion: 'Hindu', blood_group: 'A-', sch_id: 1, class_id: '6th', guardian_id: 5, orphan_status: 'Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-04-27', modified_at: null, modified_by: null },
  { first_name: 'Vimal', middle_name: null, last_name: 'Patel', email: 'vimal.patel@example.com', dob: '2008-05-05', gender: 'Male', aadhaar_number: '491234567890', caste: 'OC', religion: 'Hindu', blood_group: 'A+', sch_id: 3, class_id: '8th', guardian_id: 4, orphan_status: 'Orphan', image_url: studentBoy, is_active: true, created_at: '2024-04-28', modified_at: null, modified_by: null },
  { first_name: 'Neerja', middle_name: null, last_name: 'Bose', email: 'neerja.bose@example.com', dob: '2011-01-16', gender: 'Female', aadhaar_number: '501234567891', caste: 'SC', religion: 'Hindu', blood_group: 'O-', sch_id: 2, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-04-29', modified_at: null, modified_by: null },
  { first_name: 'Rakesh', middle_name: null, last_name: 'Gupta', email: 'rakesh.gupta@example.com', dob: '2009-06-22', gender: 'Male', aadhaar_number: '511234567892', caste: 'BC-B', religion: 'Hindu', blood_group: 'B+', sch_id: 1, class_id: '7th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-04-30', modified_at: null, modified_by: null },
  { first_name: 'Meenal', middle_name: null, last_name: 'Reddy', email: 'meenal.reddy@example.com', dob: '2010-10-15', gender: 'Female', aadhaar_number: '521234567893', caste: 'BC-A', religion: 'Hindu', blood_group: 'AB+', sch_id: 1, class_id: '6th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-05-01', modified_at: null, modified_by: null },
  { first_name: 'Saurabh', middle_name: null, last_name: 'Sharma', email: 'saurabh.sharma@example.com', dob: '2008-04-26', gender: 'Male', aadhaar_number: '531234567894', caste: 'OC', religion: 'Hindu', blood_group: 'A+', sch_id: 2, class_id: '8th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy, is_active: true, created_at: '2024-05-02', modified_at: null, modified_by: null },
  { first_name: 'Madhuri', middle_name: null, last_name: 'Chopra', email: 'madhuri.chopra@example.com', dob: '2011-08-01', gender: 'Female', aadhaar_number: '541234567895', caste: 'SC', religion: 'Hindu', blood_group: 'B-', sch_id: 3, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-05-03', modified_at: null, modified_by: null },
  { first_name: 'Nitin', middle_name: null, last_name: 'Kumar', email: 'nitin.kumar@example.com', dob: '2009-03-13', gender: 'Male', aadhaar_number: '551234567896', caste: 'BC-B', religion: 'Hindu', blood_group: 'A-', sch_id: 1, class_id: '7th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-05-04', modified_at: null, modified_by: null },
  { first_name: 'Kajal', middle_name: null, last_name: 'Reddy', email: 'kajal.reddy@example.com', dob: '2010-12-11', gender: 'Female', aadhaar_number: '561234567897', caste: 'BC-A', religion: 'Hindu', blood_group: 'O+', sch_id: 2, class_id: '6th', guardian_id: 1, orphan_status: 'Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-05-05', modified_at: null, modified_by: null },
  { first_name: 'Mukul', middle_name: null, last_name: 'Patel', email: 'mukul.patel@example.com', dob: '2008-07-23', gender: 'Male', aadhaar_number: '571234567898', caste: 'OC', religion: 'Hindu', blood_group: 'AB+', sch_id: 3, class_id: '8th', guardian_id: 4, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: true, created_at: '2024-05-06', modified_at: null, modified_by: null },
  { first_name: 'Bhavna', middle_name: null, last_name: 'Sharma', email: 'bhavna.sharma@example.com', dob: '2011-05-02', gender: 'Female', aadhaar_number: '581234567899', caste: 'SC', religion: 'Hindu', blood_group: 'A-', sch_id: 1, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-05-07', modified_at: null, modified_by: null },
  { first_name: 'Sujeet', middle_name: null, last_name: 'Rao', email: 'sujeet.rao@example.com', dob: '2009-11-27', gender: 'Male', aadhaar_number: '591234567890', caste: 'BC-B', religion: 'Hindu', blood_group: 'B+', sch_id: 1, class_id: '7th', guardian_id: 1, orphan_status: 'Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-05-08', modified_at: null, modified_by: null },
  { first_name: 'Neeraj', middle_name: null, last_name: 'Gupta', email: 'neeraj.gupta@example.com', dob: '2010-08-06', gender: 'Male', aadhaar_number: '601234567891', caste: 'OC', religion: 'Hindu', blood_group: 'A+', sch_id: 2, class_id: '6th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: true, created_at: '2024-05-09', modified_at: null, modified_by: null },
  { first_name: 'Pooja', middle_name: null, last_name: 'Das', email: 'pooja.das@example.com', dob: '2011-03-07', gender: 'Female', aadhaar_number: '611234567892', caste: 'BC-A', religion: 'Hindu', blood_group: 'O-', sch_id: 3, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-05-10', modified_at: null, modified_by: null },
  { first_name: 'Sanjay', middle_name: null, last_name: 'Reddy', email: 'sanjay.reddy@example.com', dob: '2008-02-10', gender: 'Male', aadhaar_number: '621234567893', caste: 'BC-B', religion: 'Hindu', blood_group: 'AB+', sch_id: 1, class_id: '8th', guardian_id: 1, orphan_status: 'Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-05-11', modified_at: null, modified_by: null },
  { first_name: 'Megha', middle_name: null, last_name: 'Sharma', email: 'megha.sharma@example.com', dob: '2010-10-25', gender: 'Female', aadhaar_number: '631234567894', caste: 'SC', religion: 'Hindu', blood_group: 'AB-', sch_id: 2, class_id: '6th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-05-12', modified_at: null, modified_by: null },
  { first_name: 'Vikash', middle_name: null, last_name: 'Kumar', email: 'vikash.kumar@example.com', dob: '2009-04-17', gender: 'Male', aadhaar_number: '641234567895', caste: 'OC', religion: 'Hindu', blood_group: 'O+', sch_id: 3, class_id: '7th', guardian_id: 4, orphan_status: 'Orphan', image_url: studentBoy, is_active: true, created_at: '2024-05-13', modified_at: null, modified_by: null },
  { first_name: 'Payal', middle_name: null, last_name: 'Verma', email: 'payal.verma@example.com', dob: '2011-06-18', gender: 'Female', aadhaar_number: '651234567896', caste: 'BC-A', religion: 'Hindu', blood_group: 'A-', sch_id: 1, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-05-14', modified_at: null, modified_by: null },
  { first_name: 'Ritik', middle_name: null, last_name: 'Patel', email: 'ritik.patel@example.com', dob: '2008-01-01', gender: 'Male', aadhaar_number: '661234567897', caste: 'BC-B', religion: 'Hindu', blood_group: 'AB+', sch_id: 2, class_id: '8th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy, is_active: true, created_at: '2024-05-15', modified_at: null, modified_by: null },
  { first_name: 'Sonal', middle_name: null, last_name: 'Rao', email: 'sonal.rao@example.com', dob: '2010-04-07', gender: 'Female', aadhaar_number: '671234567898', caste: 'BC-A', religion: 'Hindu', blood_group: 'O+', sch_id: 3, class_id: '6th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-05-16', modified_at: null, modified_by: null },
  { first_name: 'Amit', middle_name: null, last_name: 'Gupta', email: 'amit.gupta@example.com', dob: '2009-12-12', gender: 'Male', aadhaar_number: '681234567899', caste: 'OC', religion: 'Hindu', blood_group: 'B-', sch_id: 1, class_id: '7th', guardian_id: 2, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-05-17', modified_at: null, modified_by: null },
  { first_name: 'Ritu', middle_name: null, last_name: 'Sharma', email: 'ritu.sharma@example.com', dob: '2011-08-30', gender: 'Female', aadhaar_number: '691234567890', caste: 'SC', religion: 'Hindu', blood_group: 'A-', sch_id: 2, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-05-18', modified_at: null, modified_by: null },
  { first_name: 'Nilesh', middle_name: null, last_name: 'Kumar', email: 'nilesh.kumar@example.com', dob: '2008-03-06', gender: 'Male', aadhaar_number: '701234567891', caste: 'BC-B', religion: 'Hindu', blood_group: 'A+', sch_id: 3, class_id: '8th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-05-19', modified_at: null, modified_by: null },
  { first_name: 'Kavitha', middle_name: null, last_name: 'Reddy', email: 'kavitha.reddy@example.com', dob: '2010-09-15', gender: 'Female', aadhaar_number: '711234567892', caste: 'BC-A', religion: 'Hindu', blood_group: 'O-', sch_id: 1, class_id: '6th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-05-20', modified_at: null, modified_by: null },
  { first_name: 'Himanshu', middle_name: null, last_name: 'Patel', email: 'himanshu.patel@example.com', dob: '2009-06-17', gender: 'Male', aadhaar_number: '721234567893', caste: 'OC', religion: 'Hindu', blood_group: 'B+', sch_id: 2, class_id: '7th', guardian_id: 2, orphan_status: 'Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-05-21', modified_at: null, modified_by: null },
  { first_name: 'Jyoti', middle_name: null, last_name: 'Sharma', email: 'jyoti.sharma@example.com', dob: '2011-11-23', gender: 'Female', aadhaar_number: '731234567894', caste: 'SC', religion: 'Hindu', blood_group: 'AB-', sch_id: 3, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-05-22', modified_at: null, modified_by: null },
  { first_name: 'Dinesh', middle_name: null, last_name: 'Reddy', email: 'dinesh.reddy@example.com', dob: '2008-08-18', gender: 'Male', aadhaar_number: '741234567895', caste: 'BC-B', religion: 'Hindu', blood_group: 'A+', sch_id: 1, class_id: '8th', guardian_id: 1, orphan_status: 'Semi Orphan', image_url: studentBoy, is_active: true, created_at: '2024-05-23', modified_at: null, modified_by: null },
  { first_name: 'Lavanya', middle_name: null, last_name: 'Verma', email: 'lavanya.verma@example.com', dob: '2010-05-29', gender: 'Female', aadhaar_number: '751234567896', caste: 'BC-A', religion: 'Hindu', blood_group: 'O+', sch_id: 2, class_id: '6th', guardian_id: 5, orphan_status: 'Orphan', image_url: studentGirl2, is_active: true, created_at: '2024-05-24', modified_at: null, modified_by: null },
  { first_name: 'Kunal', middle_name: null, last_name: 'Sharma', email: 'kunal.sharma2@example.com', dob: '2009-01-24', gender: 'Male', aadhaar_number: '761234567897', caste: 'OC', religion: 'Hindu', blood_group: 'B-', sch_id: 3, class_id: '7th', guardian_id: 4, orphan_status: 'Semi Orphan', image_url: studentBoy2, is_active: true, created_at: '2024-05-25', modified_at: null, modified_by: null },
  { first_name: 'Puja', middle_name: null, last_name: 'Agarwal', email: 'puja.agarwal@example.com', dob: '2011-03-20', gender: 'Female', aadhaar_number: '771234567898', caste: 'BC-C', religion: 'Hindu', blood_group: 'AB+', sch_id: 1, class_id: '5th', guardian_id: 5, orphan_status: 'Semi Orphan', image_url: studentGirl, is_active: true, created_at: '2024-05-26', modified_at: null, modified_by: null },
];

export let MOCK_STUDENTS: Student[] = [
  ...BASE_STUDENTS,
  ...ADDITIONAL_STUDENTS.map((s, index) => ({ ...s, student_id: 8 + index, created_by: 'admin' })),
];

export let MOCK_SPONSORS: Sponsor[] = [
  { sponsor_id: 1, sponsorName: 'Infosys Foundation', email: 'contact@infosys.com', dob: '1981-07-02', ph_no: '8000001111', loc: 'Bengaluru, Karnataka', type: 'Organisation', nationality: 'Indian', contrib: '5000', is_active: true, created_at: '2024-04-01', created_by: 'admin', modified_at: null, modified_by: null, image_url: studentBoy },
  { sponsor_id: 2, sponsorName: 'Anjali Mehta', email: 'anjali.m@gmail.com', dob: '1985-03-15', ph_no: '9700002222', loc: 'Mumbai, Maharashtra', type: 'Individual', nationality: 'Indian', contrib: 'School bags and books', is_active: true, created_at: '2024-04-02', created_by: 'admin', modified_at: null, modified_by: null, image_url: studentGirl },
  { sponsor_id: 3, sponsorName: 'TCS Cares Trust', email: 'csr@tcs.com', dob: '1968-04-01', ph_no: '8000003333', loc: 'Mumbai, Maharashtra', type: 'Organisation', nationality: 'Indian', contrib: '3000', is_active: true, created_at: '2024-04-03', created_by: 'admin', modified_at: null, modified_by: null, image_url: studentBoy2 },
  { sponsor_id: 4, sponsorName: 'Prakash Rao', email: 'prakash.r@yahoo.com', dob: '1972-09-20', ph_no: '9900004444', loc: 'Hyderabad, Telangana', type: 'Individual', nationality: 'Indian', contrib: 'Monthly groceries', is_active: false, created_at: '2024-04-04', created_by: 'admin', modified_at: null, modified_by: null, image_url: studentGirl2 },
];
export let MOCK_STUDENT_SPONSORS: StudentSponsor[] = [
  { id: 1, std_id: 1, spn_id: 1, assigned_date: '2024-05-01', is_active: true, created_at: '2024-05-01', created_by: 'admin', modified_at: null, modified_by: null },
  { id: 2, std_id: 3, spn_id: 2, assigned_date: '2024-05-02', is_active: true, created_at: '2024-05-02', created_by: 'admin', modified_at: null, modified_by: null },
  { id: 3, std_id: 5, spn_id: 1, assigned_date: '2024-05-03', is_active: true, created_at: '2024-05-03', created_by: 'admin', modified_at: null, modified_by: null },
];
export let MOCK_REMINDERS: Reminder[] = [
  { rem_id: 1, title: 'Annual Sports Day', description: 'All students must register before 10th December.', event_date: '2025-12-15', venue: 'ZP High School Ground, Warangal', st_id_csv: 1, dist_ids_csv: '1,2', mndl_ids_csv: null, vil_ids_csv: null, sch_ids_csv: null, status: true, created_by: 1, created_at: '2025-11-01', updated_at: null },
  { rem_id: 2, title: 'Fee Submission Deadline', description: 'Last date for fee submission. Please ensure timely payment.', event_date: '2025-11-30', venue: 'Online / School Office', st_id_csv: null, dist_ids_csv: null, mndl_ids_csv: null, vil_ids_csv: null, sch_ids_csv: null, status: true, created_by: 1, created_at: '2025-10-15', updated_at: null },
];

export const buildStudentView = (s: Student): StudentView => {
  const school = MOCK_SCHOOLS.find(sc => sc.sch_id === s.sch_id)!;
  const village = MOCK_VILLAGES.find(v => v.vil_id === school.vil_id)!;
  const mandal = MOCK_MANDALS.find(m => m.mndl_id === village.mndl_id)!;
  const district = MOCK_DISTRICTS.find(d => d.dist_id === mandal.dist_id)!;
  const state = MOCK_STATES.find(st => st.st_id === district.st_id)!;
  const guardian = MOCK_GUARDIANS.find(g => g.guardian_id === s.guardian_id)!;
  const rel = MOCK_RELATIONSHIPS.find(r => r.relationship_id === guardian.relation)!;
  const assignment = MOCK_STUDENT_SPONSORS.find(ss => ss.std_id === s.student_id && ss.is_active);
  const sponsor = assignment ? MOCK_SPONSORS.find(sp => sp.sponsor_id === assignment.spn_id) : null;
  return {
    student_id: s.student_id, full_name: [s.first_name, s.middle_name, s.last_name].filter(Boolean).join(' '), email: s.email, dob: s.dob, gender: s.gender, aadhaar_number: s.aadhaar_number, caste: s.caste, religion: s.religion, blood_group: s.blood_group, class_id: s.class_id, orphan_status: s.orphan_status, image_url: s.image_url, is_active: s.is_active, created_at: s.created_at, created_by: s.created_by,
    sch_id: school.sch_id, sch_name: school.sch_name, sch_address: school.sch_address, vil_id: village.vil_id, vil_name: village.vil_name, mndl_id: mandal.mndl_id, mndl_name: mandal.mndl_name, dist_id: district.dist_id, dist_name: district.dist_name, st_id: state.st_id, st_name: state.st_name,
    guardian_id: guardian.guardian_id, guardian_full_name: [guardian.first_name, guardian.middle_name, guardian.last_name].filter(Boolean).join(' '), guardian_phone: guardian.phone_number, guardian_relation_name: rel.relationship_name, guardian_occ: guardian.occ,
    sponsor_id: sponsor?.sponsor_id ?? null,
    sponsorName: sponsor?.sponsorName ?? null,
    sponsor_type: sponsor?.type ?? null,
  };
};

export const buildSponsorView = (sp: Sponsor): SponsorView => ({
  sponsor_id: sp.sponsor_id,
  sponsorName: sp.sponsorName,
  email: sp.email,
  dob: sp.dob,
  ph_no: sp.ph_no,
  loc: sp.loc,
  type: sp.type,
  nationality: sp.nationality,
  contrib: sp.contrib,
  is_active: sp.is_active,
  created_at: sp.created_at,
  image_url: sp.image_url,
  students_count: MOCK_STUDENT_SPONSORS.filter(ss => ss.spn_id === sp.sponsor_id && ss.is_active).length,
});
