spring.application.name=saho-foundation-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/SaHo
spring.datasource.username=postgres
spring.datasource.password=1234

spring.datasource.driver-class-name=org.postgresql.Driver